<Project>
  <Target Name="DisablePreserializedResourcesForVsct" BeforeTargets="GenerateResources">
    <PropertyGroup>
      <GenerateResourceUsePreserializedResources>false</GenerateResourceUsePreserializedResources>
    </PropertyGroup>
  </Target>

  <ItemGroup>
    <Content Remove="Menus.vsct" />
    <VSCTCompile Include="Menus.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
  </ItemGroup>
</Project>
